#!/bin/bash

CONT_NAME='ruby-cv'
RUN_NAME="run-${CONT_NAME}"

if [[ $(basename $0) == 'rubocop' ]]
then
    TASK='shell'
    TTY=''
    COMMAND="rubocop ${@:2}"
else
    TTY='--tty'
    case $1 in
    'shell')
        TASK='shell'
        COMMAND='bash'
        ;;
    'build')
        TASK='shell'
        COMMAND="ruby ./build.rb ${@:2}"
        ;;
    *)
        TASK=$1
        ;;
    esac
fi

case $TASK in
'run')
    docker build --tag ${CONT_NAME} $(dirname $0)

    docker run \
        --rm --interactive ${TTY} \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/usr/local/src \
        --name ${RUN_NAME} \
        ${CONT_NAME} bash
    ;;
'shell')
    docker container exec \
        --interactive ${TTY} \
        ${RUN_NAME} ${COMMAND}

    rm -rf .cache
    ;;
*)
    echo "run from the project working directory"
    echo "../docker/container run        {start container}"
    echo "../docker/container shell      {bash}"
    echo "../docker/container rubocop    {rubocop}"
    ;;
esac
